# Site specific settings
title: "Rucker :: Security Researcher"
name: "Rucker"
keywords: "Security, Hacking"
baseurl: ""
url: "https://ruuucker.github.io"
description: "Security Researcher"
cover: "/assets/img/cover.svg"
fanpage_id: "688484114615664"

# Site general settings
lang: "en"
lang_alternate: "pt_BR"

# Media
disqus: rucker
github: "rucker"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
